### ISSUE TITLE
AX Conditions - Add Space for a Longer Description

### ISSUE THREAD

**Issue by MelissaHall** [hhgr/AvalancheXpress#1]
Shane and the AX team would like to have the ability to add a longer description about the current conditions at AX - IE: Slow during the day, but speeds will get faster as the day progress...

Can we find a way to add more space to the current conditions box?

**Comment by AdamChlan** [comment]
@MelissaHall Do you think it's a matter of making the box wider?

Old
<img width="545" alt="screenshot 2015-10-08 13 45 31" src="https://cloud.githubusercontent.com/assets/757209/10374982/14b29d14-6dc4-11e5-8620-f6417b687315.png">

vs

New
<img width="549" alt="screenshot 2015-10-08 13 52 56" src="https://cloud.githubusercontent.com/assets/757209/10374992/21e09658-6dc4-11e5-92c9-16c4c53d8624.png">

 It may also be nice to have the sentence that describes the condition start on a new line.

**Comment by MelissaHall** [comment]
Yes - I think making it wider and having the sentence that describes the condition starting on a new line works well.
