### ISSUE TITLE
AVXP Pricing Online

### ISSUE THREAD

**Issue by derekober** [hhgr/AvalancheXpress#3]
Adam,

Received this email from our Pro Shop that handles AVXP sales in-person...They're saying the calendar portion of the Word Press website has last year's pricing and the rates page reflects the current pricing. I can't seem to locate the calendar page for editing. Can you assist me with this?

---------- Forwarded message ----------
From: Roger Gibson <sgrg77@gmail.com>
Date: Fri, Dec 11, 2015 at 5:29 PM
Subject: AX Web Site ISSUE.
To: Melissa Hall <melissa.hall@hhgr.com>
Cc: Shane Stell <shane.stell@hhgr.com>

Melissa, 

Working on the update to the Quick Hitter I prepared last year for AX, I noticed that on the AX Website, the updated prices HAVE been put on the Rates Page...BUT NOT on the HOURS Calendars where we spell out the prices for those days.

**Comment by AdamChlan** [comment]
Yes, I can get these updated. This must have been from the recent changes that Melissa had for pricing.

**Comment by derekober** [comment]
No worries! The pricings are just slightly different. A couple $’s here and there.

Derek A. Ober
Sales and Marketing Administrator
Heritage Hills
717.755.0123 ext. 1684
717.424.1566

**Comment by AdamChlan** [comment]
Okay, this is updated.

**Comment by derekober** [comment]
Thank you!

Derek A. Ober
Sales and Marketing Administrator
Heritage Hills
717.755.0123 ext. 1684
717.424.1566
