### ISSUE TITLE
Holiday Skating Hours

### ISSUE THREAD

**Issue by derekober** [hhgr/AvalancheXpress#4]
Adam,

I have updated AVXP's Facebook & the Alert on AVXP.com but can you possibly update the calendar page for the following date's skating hours? 

Christmas holiday week hours:
Wednesday, 12/23..4-9pm
Thursday, 12/24..1-5pm
Christmas Day .. Closed
12/26 – 1/3 .. 1pm – 9pm

**Comment by AdamChlan** [comment]
Derek, is this the page you are trying to edit?

http://avalanchexpress.com/hours/holiday-hours/ <http://avalanchexpress.com/hours/holiday-hours/>

If so, you should be able to click the edit button on the page and edit those lines. Do you want to give it a shot?

**Comment by derekober** [comment]
Ah, I think Melissa and I were under the impression that the calendar for specific dates would need editing. Turns out you just have it set up to direct to the page you just provided for those dates. Thank you!!

**Comment by derekober** [comment]
I think the calendar here: http://avalanchexpress.com/hours/ would simply need updated so that 12/28-12/31 and 1/1-1/3 should all be the green "special" hours following the latest update we received from AVXP management. The hours currently do not match on the hours/calendar as they are on the special hours page.

**Comment by AdamChlan** [comment]
Okay this has been updated. Closing this out.

**Comment by AdamChlan** [comment]
@derekober should 26th be green as well?
